FROM php:7.3-fpm
RUN apt-get update \
    && apt-get install -y zlib1g-dev libzip-dev postgresql-client-common postgresql-client libpq-dev \
    && docker-php-ext-install zip pdo_pgsql
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /composer
ENV PATH $PATH:/composer/vendor/bin
WORKDIR /var/www